# docker-compose.yml
version: '2'

services:
  influxdb:
    image: influxdb:alpine
    ports:
     - "8083:8083" #hosts the influxdb webinterface
     - "8086:8086" #hosts the influxdb http api
    volumes:
     - ./influxdb_data:/var/lib/influxdb
     - ./influxdb.conf:/etc/influxdb/influxdb.conf:ro
    command:
      influxd -config /etc/influxdb/influxdb.conf
  telegraf:
    image: telegraf:alpine
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
